let data = [
  {
    // _id: 1,
    name: "shirt 1",
    img: "/images/1.jpg",
    price: "120",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    rating: 3,
    numberOfRating: 10,
    inStock: 10,
    category: "one",
    cupon: "kire",
    discount: 20,
    discountLimit: 50,
  },
  {
    // _id: 2,
    name: "shirt 2",
    img: "/images/2.jpg",
    price: "150",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    rating: 3.5,
    numberOfRating: 20,
    inStock: 16,
    category: "two",
  },
  {
    // _id: 3,
    name: "shirt 3",
    img: "/images/3.jpg",
    price: "80",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    rating: 5,
    numberOfRating: 10,
    inStock: 18,
    category: "one",
    cupon: "hello",
    discount: 50,
    discountLimit: 45,
  },
  {
    // _id: 4,
    name: "shirt 4",
    img: "/images/4.jpg",
    price: "125",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    rating: 2.5,
    numberOfRating: 10,
    inStock: 15,
    category: "two",
  },
  {
    // _id: 5,
    name: "shirt 5",
    img: "/images/5.jpg",
    price: "200",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    rating: 2,
    numberOfRating: 10,
    inStock: 0,
    category: "one",
  },
  {
    // _id: 6,
    name: "shirt 6",
    img: "/images/6.jpg",
    price: "250",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    rating: 4,
    numberOfRating: 50,
    inStock: 20,
    category: "three",
  },
  {
    // _id: 7,
    name: "shirt 7",
    img: "/images/4.jpg",
    price: "80",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    rating: 5,
    numberOfRating: 10,
    inStock: 18,
    category: "one",
  },
  {
    // _id: 8,
    name: "shirt 8 ",
    img: "/images/6.jpg",
    price: "80",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    rating: 5,
    numberOfRating: 10,
    inStock: 18,
    category: "one",
  },
];

export default data;
